export interface FlightAwareStatus {
  ident: string;
  ident_icao: string;
  ident_iata: string;
  fa_flight_id: string;
  operator: string;
  operator_icao: string;
  operator_iata: string;
  flight_number: string;
  registration: string;
  atc_ident?: null;
  inbound_fa_flight_id: string;
  codeshares?: (string)[] | null;
  codeshares_iata?: (string)[] | null;
  blocked: boolean;
  diverted: boolean;
  cancelled: boolean;
  position_only: boolean;
  origin: OriginOrDestination;
  destination: OriginOrDestination;
  departure_delay: number;
  arrival_delay: number;
  filed_ete: number;
  foresight_predictions_available: boolean;
  scheduled_out: string;
  estimated_out: string;
  actual_out: string;
  scheduled_off: string;
  estimated_off: string;
  actual_off: string;
  scheduled_on: string;
  estimated_on: string;
  actual_on?: null;
  scheduled_in: string;
  estimated_in: string;
  actual_in?: null;
  progress_percent: number;
  status: string;
  aircraft_type: string;
  route_distance: number;
  filed_airspeed: number;
  filed_altitude: number;
  route: string;
  baggage_claim: string;
  seats_cabin_business?: null;
  seats_cabin_coach?: null;
  seats_cabin_first?: null;
  gate_origin: string;
  gate_destination: string;
  terminal_origin: string;
  terminal_destination: string;
  type: string;
}
export interface OriginOrDestination {
  code: string;
  code_icao: string;
  code_iata: string;
  code_lid: string;
  airport_info_url: string;
}
